### ISSUE TITLE
Folders are shown as leaf nodes when matched by search that doesn't match any of their children

### ISSUE THREAD

**Issue by xavistp** [helion3/inspire-tree#119]
To reproduce this, go to the [search example](http://www.inspire-tree.com/demos/search.html) and search for "Features". The 3 top level folders are now shown as leaf nodes.

Not sure if that is expected behaviour cause no children match, so they are hidden, but I think a more appropriate behaviour for this case (where no children match but the parent does), would be to show the matching nodes as collapsed folder nodes and be able to expand them because the whole folder matches.

**Comment by viveleroi** [comment]
It's a tough call. The search was intended to filter matching nodes, and technically the children *don't* match, but I can imagine scenarios in which users want to show children as well. Currently the logic for the icon is based on *visible* child nodes (primarily to avoid soft-removed nodes), but it's working against us in this case.

It will probably require tweaking the logic a bit, ensuring I don't break soft removed/hidden scenarios, and likely adding a config to allow toggling the show or hide children aspect of the functionality.

**Comment by xavistp** [comment]
Yeah it's a tricky one, but the icon change is quite puzzling. It would awesome to add a config option.

**Comment by viveleroi** [comment]
I went in to fix the issue and wound up reworking the whole search method. It will slightly break backwards-compatibility (the search method now returns a promise) but overall this is much more capable.

Rather than adding a config, I made the node show as a collapsed folder by default, and users can now customize how matched nodes are handled. I've added a new `matched` state entirely which even has a default css style applied, making the matched nodes stand out.

However, users can completely customize/replace the method that processes matches. If someone wants to replicate the old result (node showing as a leaf, etc) they can use something like this in the tree config:

```js
search: {
    matchProcessor: function(matches) {
        matches.each(function(node) {
            node.state('matched', true);
            node.show().expandParents();
        });
    }
}
```

This will allow people to do whatever they need to for searches. Maybe someone wants to select all matching nodes - now it's trivial to do so.

**Comment by xavistp** [comment]
That sounds awesome! And so fast! When do you think there will be a release with these changes? Thanks a lot.

**Comment by viveleroi** [comment]
Just pushed 1.12

**Comment by xavistp** [comment]
Awesome! Thanks!
