### ISSUE TITLE
Add event 'sender' parameter to to handlers

### ISSUE THREAD

**Issue by jannhama** [helion3/inspire-tree#124]
In some use cases it would be handy to know if event was triggered by user or some other function. One case I'm facing now is that I need to select elements from the tree with mouse click but also outside via node.select() function. This leads to the event circle where node that is selected from outside will trigger on('node.selected') event that will try to update the outside component that initiated the change in the first place. With 'sender' parameter it would be possible to identify who triggered event and stop propagation when needed.

**Comment by viveleroi** [comment]
Can you clarify why selection logic would be running from a `node.selected` event listener? I want to make sure I agree that filtering events is the right solution.

The best way to handle what you're asking is probably for me to pass along the original DOM Event which initiated the action but that won't work 100% of the time, nor would it cover any custom logic.

You could listen directly for the DOM event. `node.click` only fires when the user has clicked on a node. The click event fires *before* the selection has changed (since we allow users to cancel it), so if the node isn't selected, it will be:

```js
tree.on('node.click', function(event, node) {
  // If it's *not* selected, and is selectable, it will become selected
  if (!node.selected() && node.selectable()) {

  }
});
```

Another option, which works but probably isn't recommended, is to mute the event when you're programmatically triggering it:

```js
tree.on('node.selected', function(node) {
  tree.mute('node.selected');
                
  // ... other selection logic
                
  tree.unmute('node.selected');
});
```

This will for sure cause problems if a user selects a node before the event has been unmuted.

**Comment by jannhama** [comment]
Thanks for the information. I'm currently using the tree in a way that 'on.click' I'll add the children for the clicked node and then in the actual 'on.selected' I'm passing the selection to the other component. So a bit puzzled here how I should proceed.

**Comment by viveleroi** [comment]
I'm not sure what you mean by "passing the selection to the other component"?

**Comment by jannhama** [comment]
Application is meant have same selection of items in two different places. What is selected in the tree is also selected in the other component. What is selected in the other component will change selection in the tree as well. However I managed to get it working so this issue can be closed for now.

**Comment by viveleroi** [comment]
So you're trying to synchronize selections between two components? Are they both InspireTree instances, or only one? I think there are primarily two routes:

1. Have each update the other when a selection is made, but this means you need to find a way to filter/ignore circular events
2. Centralize the selection data and have both components "poll" it. If you have a data store each component can update when selection changes, it won't cause any circular events. Maybe that data store can fire an event when something *does* change and both components can parse the change and show it. You have a bit more work to do for synchronization but you avoid circular deps.

Hope those ideas help.

**Comment by jannhama** [comment]
Thanks for the answer. I have just one inspire tree instance the other component is a list. Inspire tree owns the data while selection to that data can be done in either of the components. Circular loop was bug in our code after all, it did unnecessary select call that caused circular selects :D
