### ISSUE TITLE
enhancement - break out core module

### ISSUE THREAD

**Issue by scniro** [helion3/inspire-tree#153]
Would like to foremost say, awesome project - I really dig what you've done here. I was curious what your thoughts would be on breaking the core library out into it's own module, with the full inspire-tree package consuming it as a dep.

Asking because for my usage, I am solely concerned with the core functionality as I am rolling my own rendering. I think it would be nice to pull down only what I need in this case. In the spirit of further staying lean, what are your thoughts on also not including `dist` and encouraging consumers to leverage a build process (pretty standard, speaking generally) to minify their own builds in their local development ecosystems?

Thanks.

**Comment by viveleroi** [comment]
I've actually been working on splitting the components already, but it's not easy and is something I'm planning to do with the inferno migration. I never liked these pieces being together in the first place but due to how the lib has evolved, it makes sense now. Along with such a drastic change though, I may take my time and make other changes I've long thought of.

While the npm package contains **all** files, you can still run a custom build. The core files are distributed without any DOM code and you also have access to the source. Right now that relies on the webpack define plugin to set `DOM=false`, but you *could* work with what's there.

No matter how the structure changes though, I have to continue to provide the `dist` folder because despite how common bundling tools are, I can't force everyone to use them. In fact the very first corporation to use this lib in their product can't make that switch, so I know there must be others too.

**Comment by scniro** [comment]
for serving the built files, would it be more appropriate to do so through bower? I know if both are leveraged you'd be able to exclude files per each package file. In other words, the web bower dist wouldn't care about the source files, and the npm dist wouldn't care about the built. Either way, for now I can get by by requiring the file I need directly

    let InspireTree = require('inspire-tree/dist/inspire-tree-core-bundled');

Pulling down amost 2mb down through an npm install leave me side-eyeing it 😺 I'd be happy to contribute at some point if you're open to PRs

**Comment by viveleroi** [comment]
PRs are always welcome.

I wouldn't split files up between package managers because at least in my experience, so many people are ditching bower in favor of npm. I'll keep working on splitting packages but we can't stop providing compiled dist files unless something convinces me that a vast majority of users have made the jump to bundling tools. It *might* be possible to provide the source in a separate package, but that seems overly complex just to save file space.

**Comment by scniro** [comment]
That's unfortunate to hear. Why not just commonjs an index.js file and call it a day? For anyone using npm and needing a minified file, they're 100% doing it wrong and shouldn't be a holdout on this. I'd instead urge you to justify how this is good practice.

I can't think of any major player (jQuery, lodash, etc) that does this.

**Comment by viveleroi** [comment]
Ideologically I'm in your camp, but realistically I'm not convinced that I can abandon everyone using npm without a bundler. npm is useful for package management and if a team can use it, but they cannot migrate to webpack or browserify, I don't want them left behind. 

> I can't think of any major player (jQuery, lodash, etc) that does this.

Your two examples do *exactly* this; jQuery provides `dist/jQuery.min.js` and lodash provides `lodash.min.js`. Until client-side JS catches up to node/es6+ we're going to have a rift and many popular libs will cater to both.
