### ISSUE TITLE
Is there FULL documentation on this???

### ISSUE THREAD

**Issue by Terry-Fedirko** [helion3/inspire-tree#164]
I'm on this web site and it does tell me all the function, events API's and features BUT it does not go far enough in how each of these work.    Is there a full documentation on how to use inspire-tree (including inspire-tree-dom)???

**Comment by Terry-Fedirko** [comment]
Also, there are no examples on how to uses each of these

**Comment by viveleroi** [comment]
Can you clarify what specifically you're looking for? Everything you should need to get started is on our README, including links to the API docs. For everything else you're welcome to ask in the gitter room linked in the readme.

**Comment by Terry-Fedirko** [comment]
Hello Mike:

I see no problems with the APIs itself however, trying to configure the inspire-tree based on your information on github.

User JSFiddle to try to understand how this works, I am unable to create a collapsible tree using checkboxes for selections.     Also, instead of using ‘text’, is there a way do use html to display the data.   And….can you implement event coding directly to the ‘InspireTree’.

It would be a major help if there is a full documentation on how this thing works with examples.

Note:  Currently, I am using Kendo TreeView which works great, however, we are dealing with data points that execess over 100,000 (some cases, in the 1-5 million range).  Kendo TreeView cannot handle that much data and I assume inspire-tree can.

Best Regards,

Terry Fedirko
Senior .NET Developer
Memex Inc.

E-mail:  Terry.Fedirko@memexoee.com
Office: 905-635-1540 ext 309

**Comment by viveleroi** [comment]
1. Regarding checkbox-based selection, there's an example on the website that provides the code needed: http://www.inspire-tree.com/demos/checkboxes.html . The key is the `selection.mode: 'checkbox'` property. 

2. I'm not clear what you mean by "instead of using ‘text’, is there a way do use html". If you're asking if the `text` property supports in-line HTML, it doesn't.

3. I'm also not sure what you mean by "implement event coding directly on the `InspireTree`" but events work like most other event-driven libraries and there's an example on the README:

```
tree.on('node.added', function(event, node) {
    // node added!
});
```

4. Inspire Tree *tries* to handle large data sets but it's ultimately up to how you structure it. v2 of inspire tree is much faster than v1 but to load massive datasets you should rely on deferred loading somehow. If you have 100k root nodes, you can paginate them and only load subsets as needed, or you can only root nodes and then load children when the node's expanded, etc.

**Comment by Terry-Fedirko** [comment]
Hello Mike,


Let me give you more details on what I’m trying to do.   If you take a look at the code in JSFiddle (https://jsfiddle.net/tfedmemex/mybe5qtj/83/  If you can’t access this URL, let me know and I will send you a copy) , I’m trying to use the ‘deferredRendering’ in the InspireTreeDOM setup.    It does give you the ‘…Load More’, but when I click on it, it just append the data source at the bottom of the tree and not under ‘…Load More’ where I clicked.    Unfortunately, there is no good example of how to do this on your website (or anywhere) and using trial and error method to figure this out.

FYI:   If you have noticed bold characters in the tree, we modified one of your functions in the ‘inspire-tree-dom’ (dist)  to accept HTML tags:
function setTextContent(dom, text)
    if (text !== '') {
        dom.textContent = text;   <== dom.innerHTML = text
    }
    else {
        dom.appendChild(document.createTextNode(''));
    }
}

Best Regards,

Terry Fedirko
Senior .NET Developer
Memex Inc.

E-mail:  Terry.Fedirko@memexoee.com
Office: 905-635-1540 ext 309
