### ISSUE TITLE
thoughts on using modularized lodash?

### ISSUE THREAD

**Issue by mreinstein** [helion3/inspire-tree#168]
this is more opinion than a real problem or anything.

lodash actually ships all of the individual functions as standalone modules. e.g., could do

```javascript
import { noop } = from 'lodash.noop';
```

This will likely result in smaller bundle sizes as we'd only be including the parts of lodash that we actually use.

**Comment by viveleroi** [comment]
Now that I don't package lodash, I'm all for it. Some time in v1, I did this, because webpack v1 didn't support tree-shaking. jdalton wrote a plugin to do it specifically for lodash, but a) it wasn't perfect, and b) didn't work with other tooling I had and required lodash proper (and never allowed chaining).

Since v2 drops bundling lodash, something I was unsure about though, I can go back to this. Especially now that tooling is so common.

**Comment by scniro** [comment]
@viveleroi hey I see this is closed out but notice all of lodash is still being used. Were you able to make any forward progress on this? I may be able to send a PR your way to get this going if you haven't yet been able to get to it. I would like to reduce my bundle size and this would surely help

**Comment by viveleroi** [comment]
It's blocked by the client-side module problem. Users who do not use module bundlers (RequireJS users, global script users) need a way to translate `lodash.something` into `_.something`. 

I toyed around with this a few months ago and couldn't see a solution. RequireJS has no concept of "destructuring" an object. It might be possible to build on my end but I would need three different distribution files - a browser file that maps `lodash.something` to the `_.something` global/property,  one for node, but there's still no clear answer for AMD/Require users.

I'm certainly interested if you know a way to solve that.
