### ISSUE TITLE
Not able to load inspire tree using requirejs

### ISSUE THREAD

**Issue by gyancse08** [helion3/inspire-tree#170]
It has a lodash dependency but even after adding this dependency I am seeing bunch of error which loading inspire-tree. Attaching screenshot. 
![image](https://user-images.githubusercontent.com/10982237/30567486-809f7280-9c85-11e7-8cd0-df4d6e22f901.png)

**Comment by viveleroi** [comment]
Those errors don't relate to InspireTree, or lodash, and as far as I can tell they're unrelated to requirejs. Judging by the naming I'd bet a Chrome extension is throwing errors. 

If there are errors with InspireTree specifically I can help, but I'm pretty confident it's working just fine with RequireJS because I'm using it that way myself.
