### ISSUE TITLE
Crypto function doesn't exist in browsers

### ISSUE THREAD

**Issue by ianthurlow** [helion3/inspire-tree#177]
This bit of code is failing for me in the newest version in both updated Chrome (63.0) and Firefox:

`
var rng = function nodeRNG() {
  return crypto.randomBytes(16);
};
`

Console says:
Uncaught TypeError: crypto.randomBytes is not a function
    at nodeRNG (inspire-tree.js:22)
    at v4 (inspire-tree.js:58)

Am I doing something wrong here? I updated from 3.0.1 to 4.3.0, but it looks like it's now using some node.js functions instead of pure browser side javascript. Thanks and cheers.

**Comment by viveleroi** [comment]
Yikes. Our code hasn't changed so I bet an update to the build tools broke this.

**Comment by viveleroi** [comment]
Looks like this was broken due a build tool issue: https://github.com/rollup/rollup-plugin-node-resolve/issues/136

I've revert to the last working version and deploy.

**Comment by trevorgithub** [comment]
I tried loading inspire-tree.min.js (and later inspire-tree.js), which I got from npm:

"inspire-tree": "^4.3.0",
"inspire-tree-dom": "^4.0.3"

copied from nodemodule\inspire-tree\dist (is that the correct files to use for web, or they intended only for use in node?) using the AMD approach, but it failed with a similar error as originally reported:


`GET http://localhost:3000/crypto.js net::ERR_ABORTED`
`req.load @ require.min.js:formatted:1111`
`load @ require.min.js:formatted:988`
`load @ require.min.js:formatted:488`
`fetch @ require.min.js:formatted:481`
`check @ require.min.js:formatted:498`
`enable @ require.min.js:formatted:688`
`enable @ require.min.js:formatted:922`
`(anonymous) @ require.min.js:formatted:678`
`(anonymous) @ require.min.js:formatted:68`
`each @ require.min.js:formatted:17`
`enable @ require.min.js:formatted:649`
`init @ require.min.js:formatted:455`
`callGetModule @ require.min.js:formatted:708`
`completeLoad @ require.min.js:formatted:939`
`onScriptLoad @ require.min.js:formatted:997`


`Uncaught Error: Script error for "crypto", needed by: inspire-tree`
`http://requirejs.org/docs/errors.html#scripterror`
`    at makeError (require.min.js:formatted:88)`
`    at HTMLScriptElement.onScriptError (require.min.js:formatted:1014)`
`makeError @ require.min.js:formatted:88`
`onScriptError @ require.min.js:formatted:1014`

When I took the inspire-tree.min.js from http://www.inspire-tree.com/, it works fine.

Perhaps this is expected, as the issue is still in the Open state.  I just wanted to give a heads up, in case this wasn't already known. (Or maybe I'm using it wrong...)

**Comment by viveleroi** [comment]
Which specific inspire-tree version are you using? I tested 4.3.1 and it's working correctly using RequireJS: https://codepen.io/helion3/pen/XZpEPd

**Comment by trevorgithub** [comment]
I think I'm using 4.3.0, as this is the version installed when I run
` npm install inspire-tree --save-dev`

Here's part of my package.json:

 "devDependencies": {
    "grunt": "^1.0.1",
    "grunt-contrib-jshint": "^1.1.0",
    "grunt-contrib-watch": "^1.0.0",
    "inspire-tree": "^4.3.0",
    "inspire-tree-dom": "^4.0.3"
  },

**Comment by viveleroi** [comment]
You'll need to upgrade to 4.3.1.

**Comment by trevorgithub** [comment]
Will I have to get it from git?  It seems npm still installs 4.3.0 when I use the command above.

**Comment by viveleroi** [comment]
My mistake, the publish failed so I've gone ahead and published again. It should be available now.

**Comment by trevorgithub** [comment]
Thanks.  I can confirm that 4.3.1 works for me.

**Comment by viveleroi** [comment]
rollup-plugin-node-resolve has corrected this issue on their end so I can re-update safely. Thanks.
