### ISSUE TITLE
Feature Request: set(State) takes object

### ISSUE THREAD

**Issue by MrNice** [helion3/inspire-tree#179]
In react, you can update multiple pieces of UI state at once with `this.setState({ a: 1, b: 2})`, which allows a single rerender to apply changes.

It would be nice if the node `set` method could take an object and update multiple pieces of state.

**Comment by viveleroi** [comment]
`set()` and `state()` are different. I believe you meant `state` because that's essentially the equivalent to React's `setState`. `set` also accepts prop/val arguments but it's more generic and isn't state-stored. It's an alternate way of doing `node.someProp = someVal`, but with a dirty trigger afterward.

`set` could also benefit from the object approach though, so I may leave this open.

**Comment by viveleroi** [comment]
In thinking more about the terminology, `set` is more like `_.set` (except without path support) and isn't meant for "merging" objects. Since natively this is `Object.assign`, I've added `node.assign(...sources)`.
