### ISSUE TITLE
Feature Request:  tree method to detect whether this tree is filtered

### ISSUE THREAD

**Issue by suxiaogang** [helion3/inspire-tree#181]
IMO, this api should return *true* only in condition that `scope.tree.search(predicate)` is called and at least one node is matched.

**Comment by viveleroi** [comment]
On consideration, I've decided not to add any new methods for this. 

Currently, you can do this by checking `tree.matched().length > 1`. `matched()` returns an array of nodes that were matched by the last search. A node's `matched` state will be `false` before a search or after `clearSearch` is called.

In the upcoming v5, you'll be able to also use `tree.find(node => node.matched())` which is faster since it exits after finding the first match.

If you have a use case in which neither of those work for your needs, let me know.
