### ISSUE TITLE
Uncaught TypeError: Cannot read property '$EV' of null

### ISSUE THREAD

**Issue by makaiqian** [helion3/inspire-tree#185]
Hey,

I use inspire-tree to do drag-and-drop. When I dragged dom repeatedly, the console throws an error:

`Uncaught TypeError: Cannot read property '$EV' of null`

version: 
Inspire Tree: @4.3.1
Inspire Tree Dom: @4.0.5

But I changed to the official website DEMO, there is no such problem. version:
Inspire Tree: @4.2.1
Inspire Tree Dom: @4.0.3

Please help me to solve this problem next version?

Thanks in advance. ^_^

**Comment by viveleroi** [comment]
Please provide your full InspireTree configuration, otherwise I won't be able to reproduce the issue. However, I've seen this before when both drag and drop and editing modes are enabled, and it's caused by Inferno, the view library we use in our DOM package, so I'm unsure there's anything we can do.

https://github.com/helion3/inspire-tree-dom/issues/18
