### ISSUE TITLE
Indenterminate state not set to true when children are checked programatically

### ISSUE THREAD

**Issue by grzegorztomasiak** [helion3/inspire-tree#192]
Given

            var tree = new InspireTree({
                selection: {
                    mode: 'checkbox'
                },
                data: [{
                    text: 'foo',
                    children: [{
                        text: 'bar',
                        itree: {
                            state: {
                                checked: true
                            }
                        }
                    }]
                }]
            });

`console.log(tree.nodes());` returns I assume prepared nodes for view, however node `foo` indeterminate state stays at false, shouldn't be true? Since `bar` is checked or am I missing something?

**Comment by viveleroi** [comment]
I would suggest using the API to check a node. (`tree.node('the-id').check()`) because that initiates the internal indeterminate logic.

In this scenario you're providing the initial state so it's up to you to provide the specific state you want for everything, there's no logic to validate everything you're providing. If you want to continue with this state approach, you can set the `itree.state.indeterminate` property on the parent node.
