### ISSUE TITLE
optional classes added to nodes

### ISSUE THREAD

**Issue by russellyoung** [helion3/inspire-tree#25]
I'm not sure how you are working the editing on this code, but I have a suggestion. I would like to support different styles for different entries - specifically, the family list I am using has each person with child nodes of children and of spouse(s), and I want to style the spouses differently than the children. To do this I made the following addition to the code:

line 266 in src/dom.js:
```javascript
    if (!tree.config.showCheckboxes) {
        classNames.push(current.state.icon || (hasVisibleChildren ? 'icon-folder' : 'icon-file-empty'));
    }
    // start of new code
    if (node.extra_classes)
        Array.prototype.push.apply(classNames, node.extra_classes);
    // end of added code
    return (0, _h2.default)('a.' + classNames.join('.'), {
```

This adds the extra classes in node.extra_classes to the node classes. This seems to me to be a relatively simple change that will add to the flexibility of the package.

russell young

**Comment by viveleroi** [comment]
I could easily add support for custom and dynamic classes but I'd most likely put it on the `li`, because that's where the other state classes go and because structurally, it would allow you to select any child element.

In your example code, why did you go with `Array.prototype.push.apply`?

**Comment by russellyoung** [comment]
This is why I didn't want to edit the code directly, what I have works for me but may not be the best way to do it.

I'm not really a node.js person, the reason I'm doing this project is that my old company folded and as long as I have time I'd like to get a little practice in something new, so if this not a good way I'd appreciate knowing why. I know here it doesn't make too much difference, but I wanted to push the contents of the array without reallocating, as would be done with concat. Using a loop would be fine, but in interpreted languages I always figure the language internals use fewer resources than a loop. Of course in this case it would not be more than one or two objects so it doesn't really save anything - is it that it makes the code more obscure to maintainers, or is there some other reason `apply` is not appropriate?

**Comment by viveleroi** [comment]
You don't have access to edit the code directly, so even if you made these changes on your own fork and submitted a PR it would be reviewed.

The tree already has an `itree.li.attributes` structure that should allow users a way to set custom attributes on a tree node. Using that we can allow for an array, function, or string. Because `class` is a reserved word some older javascript versions don't allow it as an object property so it's best to support both `class` and `className`. React users will be familiar with `className` and is probably the most common alternative.

To be clear, node.js isn't used for the end result, only for tools necessary to develop, test, and build it.

Regarding `Array.prototype.push.apply(classNames, node.extra_classes);`, it's redundant of `concat` and has no performance benefits. You're effectively substituting one native method for another which is generally unlikely to give you a performance gain. JSPerf is down pending a new version but there are several stackoverflow discussions regarding the lack of any performance advantage of either method.
