### ISSUE TITLE
Can get inspire-tree to show. What am I doing wrong?

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [helion3/inspire-tree#81]
Hi. I'm trying to use inspire-tree to show/hide different layers on a map. I'm just at the begining of this project, and I can get to see any tree being generated. 

https://github.com/tangrams/ux_layers/blob/gh-pages/src/UxLayers.js#L56-L67

I will appreciate some guidance on it. Thanks

**Comment by viveleroi** [comment]
I'm not familiar with the DOM system you're using, but I'm willing to bet that `L.DomUtil.create` is giving you a wrapped object, not the final DOM element. Hypothetically it might be giving you an `LDomElement` which is a custom object and can't be understood by inspire tree. 

Objects/classes like those typically *generate* HTMLElements when they actually render. If there's a way for you to access that final DOM element, InspireTree should work. There's also a way for you to write a custom rendering system (no need to use the bundled virtual-dom system when folks already have something) but I'm not sure that's the right choice for your needs.

It's hard to debug code by reading alone (without seeing the results).

**Comment by patriciogonzalezvivo** [comment]
Calling it by the class name `.ux_layers-tree` also does nothing : (

```
                var tree = new InspireTree({
                    target: '.ux_layers-tree',
                    selection: {
                        mode: 'checkbox'
                    },
                    data: tree_data
                });
```

**Comment by patriciogonzalezvivo** [comment]
Also, here is the url of it: https://tangrams.github.io/ux_layers/#4/-25.01/-62.49

`tree` is exposed... you can call it from the console.

Thanks!

**Comment by viveleroi** [comment]
A quick look at that page, I don't see any element with a class of `ux_layers-tree`. I see a few js errors, so my bet is that the element isn't properly part of the final DOM tree.

**Comment by patriciogonzalezvivo** [comment]
InspiredTree seams to see it and pick it up, to the point that add the class `inspire-tree` to it 

![screen shot 2016-11-09 at 2 51 16 pm](https://cloud.githubusercontent.com/assets/346914/20152378/032987d6-a68c-11e6-9856-5dcc383c898c.png)

**Comment by viveleroi** [comment]
Ok, I've realized my adblocker was causing issues. It was blocking calls to `rawgit.com` which was breaking the whole thing.

`tree.nodes()` returned an empty array so I tried adding one (`tree.addNode({ text: 'test' });`) and it errors with "`_.isArrayLike` is not a function." Sounds like it's using an older version of lodash, which since you're using es6/2015 imports, would be coming from the `npm_modules/lodash` directory. InspireTree doesn't define lodash as a peer dependency (maybe it should) so the first step here is to update lodash and rebuild the js.

**Comment by viveleroi** [comment]
Also, if lodash is out of date, I'm betting that the errors it's triggering are being captured by the inspire tree data loader and they get contained within the promise. It's possible that it's fired in the `data.loaderror` event. I should test that and see, but also should probably move lodash to a peerDep.

**Comment by patriciogonzalezvivo** [comment]
I will give it a thanks very much!

**Comment by patriciogonzalezvivo** [comment]
I see... so that needs to be done on Inspire-tree? what I should do exactly? (sorry for the pain)

**Comment by viveleroi** [comment]
Your copy of lodash is outdated for what InspireTree needs, so on your end, updating lodash should resolve the issue. I'm betting you have v3.x. My super quick test of lodash 3.10.1 causes the data loader promise to reject because of the same error: `TypeError: _.isArrayLike is not a function` so I'm confident that's the issue. 

On my end, I can make sure InspireTree is more strict about preventing this for other people, and more vocal when there's an error on initial data load.

**Comment by patriciogonzalezvivo** [comment]
thanks again : )

**Comment by viveleroi** [comment]
I'll close this since it's not really an issue but feel free to add to it if you continue to have issues (or open new ones).
