### ISSUE TITLE
Is there a way to check a node when is created

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [helion3/inspire-tree#85]
I'm making a check tree and need to create all nodes checked. What's the best way to do that?

Thanks

**Comment by viveleroi** [comment]
You have a few choices:

1. You can set an initial state on the data itself. 

```
{
    text: 'Example',
    itree: {
        state: {
            selected: true
        }
    }
}
```

2. You can do it through the API.

```
tree.on('model.loaded', function() {
    tree.selectDeep();
});
```

Either way is fine, but the first is likely a bit more efficient because it doesn't require additional iterations of the nodes - but that's such a trivial difference especially when you don't have hundreds of nodes.

**Comment by patriciogonzalezvivo** [comment]
Thanks a lot!
